server:
  port: 8082

spring:
  application:
    name: fraud
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: fraud
      port: 27017
      host: localhost
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true